arch tests ci test run

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -1,47 +1,47 @@
-name: End to End Tests
-
-on: [push, pull_request]
-
-jobs:
-  test-e2e:
-    runs-on: ubuntu-latest
-    env:
-      REDIS_PORT: 6379
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Start database
-        run: docker compose -f docker-compose.test.yml up -d db-test
-
-      - name: Wait for database to be ready
-        run: |
-          until docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test pg_isready -U postgres | grep "accepting connections"; do
-            echo "Waiting for database to be ready..."
-            sleep 2
-          done
-          echo meeeww
-          echo "Database is ready. Listing available databases before creation:"
-          docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test psql -U postgres -l
-          echo "Creating test database if it does not exist..."
-          docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test psql -U postgres -d postgres -c "SELECT 1 FROM pg_database WHERE datname='weather_db_test';" | grep -q "1" || docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test psql -U postgres -d postgres -c "CREATE DATABASE weather_db_test;"
-          echo "Listing available databases after creation:"
-          docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test psql -U postgres -l
-        timeout-minutes: 1
-
-      - name: Run E2E tests
-        run: |
-          npm run test:e2e:docker
-
-      - name: Debug logs on failure
-        if: failure()
-        run: |
-          docker compose -f docker-compose.test.yml logs db-test
-          docker compose -f docker-compose.test.yml logs backend-test
-          docker compose -f docker-compose.test.yml logs test-e2e
-      - name: Cleanup Docker Compose
-        if: always()
-        run: |
-          docker stop db-test || true
-          docker rm db-test || true
-          docker compose -f docker-compose.test.yml down -v || true
+#name: End to End Tests
+#
+#on: [push, pull_request]
+#
+#jobs:
+#  test-e2e:
+#    runs-on: ubuntu-latest
+#    env:
+#      REDIS_PORT: 6379
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Start database
+#        run: docker compose -f docker-compose.test.yml up -d db-test
+#
+#      - name: Wait for database to be ready
+#        run: |
+#          until docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test pg_isready -U postgres | grep "accepting connections"; do
+#            echo "Waiting for database to be ready..."
+#            sleep 2
+#          done
+#          echo meeeww
+#          echo "Database is ready. Listing available databases before creation:"
+#          docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test psql -U postgres -l
+#          echo "Creating test database if it does not exist..."
+#          docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test psql -U postgres -d postgres -c "SELECT 1 FROM pg_database WHERE datname='weather_db_test';" | grep -q "1" || docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test psql -U postgres -d postgres -c "CREATE DATABASE weather_db_test;"
+#          echo "Listing available databases after creation:"
+#          docker compose --env-file .env.test.e2e.docker -f docker-compose.test.yml exec -T db-test psql -U postgres -l
+#        timeout-minutes: 1
+#
+#      - name: Run E2E tests
+#        run: |
+#          npm run test:e2e:docker
+#
+#      - name: Debug logs on failure
+#        if: failure()
+#        run: |
+#          docker compose -f docker-compose.test.yml logs db-test
+#          docker compose -f docker-compose.test.yml logs backend-test
+#          docker compose -f docker-compose.test.yml logs test-e2e
+#      - name: Cleanup Docker Compose
+#        if: always()
+#        run: |
+#          docker stop db-test || true
+#          docker rm db-test || true
+#          docker compose -f docker-compose.test.yml down -v || true
